# Generated by Django 5.0.4 on 2024-09-23 12:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Laptop",
            fields=[
                ("id_laptop", models.BigAutoField(primary_key=True, serialize=False)),
                ("laptop_name", models.CharField(max_length=50)),
                ("spec", models.CharField(max_length=100)),
                (
                    "price",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(10000)]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                ("id_rating", models.BigAutoField(primary_key=True, serialize=False)),
                ("review", models.CharField(max_length=100)),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("recommended", models.BooleanField(default=True)),
                (
                    "laptop",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="KatalogLaptop.laptop",
                    ),
                ),
            ],
        ),
    ]
