# Generated by Django 5.0.4 on 2024-10-01 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("KatalogLaptop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="laptop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="KatalogLaptop.laptop",
            ),
        ),
    ]
