# Generated by Django 5.0.4 on 2024-10-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("KatalogLaptop", "0002_alter_rating_laptop"),
    ]

    operations = [
        migrations.AddField(
            model_name="laptop",
            name="total_rating",
            field=models.FloatField(default=0),
        ),
    ]
